joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 100
  
arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
       - first_joint_base
       - second_joint_enclosure_joint
       - second_joint_base
       - third_joint_base
    
    constraints:
      goal_time: 0.3
      first_joint_base: 0.05
      grabber_fixture_left_joint: {trajectory: 0.1, goal: 0.1}
      second_joint_enclosure_joint: {trajectory: 0.1, goal: 0.1}
      second_joint_base: {trajectory: 0.1, goal: 0.1}
      third_joint_base: {trajectory: 0.1, goal: 0.1}

    stop_trajectory_duration: 0.5
    state_publish_rate: 25
    state_monitor_rate: 10
  
claw_controller:
    type: position_controllers/JointTrajectoryController
    joints:
       - grabber_fixture_left_joint
       - grabber_fixture_right_joint
    
    constraints:
      goal_time: 0.3
      stopped_velocity_tolerance: 0.05
      grabber_fixture_left_joint: {trajectory: 0.1, goal: 0.1}
      grabber_fixture_right_joint: {trajectory: 0.1, goal: 0.1}

    stop_trajectory_duration: 0.5
    state_publish_rate: 25
    state_monitor_rate: 10
  
gripper_controller:
    type: position_controllers/JointTrajectoryController
    joints:
       - left_gripper_joint
       - right_gripper_joint
    
    constraints:
      goal_time: 0.3
      stopped_velocity_tolerance: 0.05
      left_gripper_joint: {trajectory: 0.1, goal: 0.1}
      right_gripper_joint: {trajectory: 0.1, goal: 0.1}

    stop_trajectory_duration: 0.5
    state_publish_rate: 25
    state_monitor_rate: 10
