gazebo_ros_control/pid_gains:
#values tested and optimised
#the wheels need a proportional gain equal to or less 0.30, otherwise gazebo crashes
  drivewhl_l_back_joint: {p: 0.30, i: 100.0, d: 0.00001}
  drivewhl_r_back_joint: {p: 0.30, i: 100.0, d: 0.00001}
  drivewhl_l_middle_back_joint: {p: 0.30, i: 100.0, d: 0.00001}
  drivewhl_r_middle_back_joint: {p: 0.30, i: 100.0, d: 0.00001} 
  drivewhl_l_middle_front_joint: {p: 0.30, i: 100.0, d: 0.00001} 
  drivewhl_r_middle_front_joint: {p: 0.30, i: 100.0, d: 0.00001} 
  drivewhl_l_front_joint: {p: 0.30, i: 100.0, d: 0.00001}
  drivewhl_r_front_joint: {p: 0.30, i: 100.0, d: 0.00001}
 
#high proportional gain for the arm joints for a fast movement to goal with joint_trajectory_controller
#  first_joint_base: {p: 100000, i: 0.0, d: 0.00001}
#  second_joint_enclosure_joint: {p: 100000, i: 0.0, d: 0.00001}
#  second_joint_base: {p: 100000, i: 0.0, d: 0.00001}
#  third_joint_base: {p: 100000, i: 0.0, d: 0.00001}
#  grabber_fixture_left_joint: {p: 100000, i: 0.0, d: 0.00001}
#  grabber_fixture_right_joint: {p: 100000, i: 0.0, d: 0.00001}
#  left_gripper_joint: {p: 100000, i: 0.0, d: 0.00001}
#  right_gripper_joint: {p: 100000, i: 0.0, d: 0.00001}
